# Generated by Django 2.2.5 on 2019-09-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='mobile',
        ),
        migrations.AddField(
            model_name='member',
            name='city',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='member',
            name='college',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='member',
            name='profile_pic',
            field=models.ImageField(blank='True', upload_to='profile_pics'),
        ),
    ]
