# Generated by Django 2.2.5 on 2019-09-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='counting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.IntegerField(null=True)),
                ('total', models.IntegerField(null=True)),
            ],
        ),
    ]
