# Generated by Django 2.2.5 on 2019-09-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdata',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sdata',
            name='age',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sdata',
            name='fathername',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sdata',
            name='mothername',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sdata',
            name='phone',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
